# Generated by Django 5.0.6 on 2024-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.URLField(max_length=600, verbose_name='Imagen'),
        ),
    ]
